### ISSUE TITLE
Video size

### ISSUE THREAD

**Issue by gaboprieto** [hoanglm4/flutter_youtube_view#1]
Hello so far seems to work really good even with live video!

One question is there anyway to set like a BoxFit for the video widget like cover, fitwidth stuff like that?

**Comment by hoanglm4** [comment]
Hello @unmaskedd ,
I will research for your idea. 
If you have any idea, please suggest me.
Thanks

**Comment by gaboprieto** [comment]
Thanks!

Also any idea why the video wont show in android?

EDIT:
fixed it, it was my code

**Comment by hoanglm4** [comment]
Available on: `flutter_youtube_view: ^1.1.4`
Lib support three mode: none, fitWidth, fitHeight.  Default is none
