### ISSUE TITLE
Youtube Player shows 'Video unavailable' for available video

### ISSUE THREAD

**Issue by 06153** [hoanglm4/flutter_youtube_view#11]
I was able to reproduce this on unmodified repo by changing `videoId` value to `_45ZERilec0` for `YoutubeParam` in `YoutubeCustomWidget.dart`. This video itself opens in browser just fine. 

Console output:

```
flutter: onReady
flutter: onStateChange state = UNSTARTED
flutter: onStateChange state = BUFFERING
flutter: onStateChange state = UNSTARTED
```

**Comment by hoanglm4** [comment]
Hello @06153 
This video can not embed  via iframe

**Comment by 06153** [comment]
Thank you @hoanglm4 for looking into it. Just to make sure I understand correctly: the problem is with the video itself on youtube side?

**Comment by 06153** [comment]
Okay, [some users can restrict embedding their videos](https://support.google.com/youtube/answer/6301625?hl=en) so it has nothing to do with your package. Thank you again!
