### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "flutter_youtube_view":

### ISSUE THREAD

**Issue by simphiwehlabisa** [hoanglm4/flutter_youtube_view#12]
In Podfile:
        flutter_youtube_view (from `.symlinks/plugins/flutter_youtube_view/ios`)
    Specs satisfying the `flutter_youtube_view (from `.symlinks/plugins/flutter_youtube_view/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by hoanglm4** [comment]
flutter_youtube_view  using iOS deployment target: '10.0'
Which deployment target in your project?

**Comment by simphiwehlabisa** [comment]
ey i use 9 mate will sort it out thankx
