### ISSUE TITLE
How to stop autoplay ? 

### ISSUE THREAD

**Issue by nitneuq33** [hoanglm4/flutter_youtube_view#13]
I think it's not an issue but I don't succeded to not play automatically the video. Any solution ?  Thank you

**Comment by hoanglm4** [comment]
Hello @nitneuq33 ni
I'm sorry for response slow. With your require, I need add more params in this library. The week-end, I will release

**Comment by noobiek** [comment]
@hoanglm4 hi!
Any news?

Btw, thank you for your efforts!

**Comment by hoanglm4** [comment]
This option will be added to version: 1.1.5
