### ISSUE TITLE
Suggestion: Support setPlaybackRate

### ISSUE THREAD

**Issue by wongni** [hoanglm4/flutter_youtube_view#16]
I'd like to add setPlaybackRate(double rate) to the controller class so that a user can change the video playback speed from 0.5x to 2.0x.

**Comment by hoanglm4** [comment]
Hi @wongni ,
I will add all  [Youtube Player API function](https://developers.google.com/youtube/iframe_api_reference). But currently, I very busy. I will add  them in next month.

**Comment by hoanglm4** [comment]
Implemented in version: 1.1.6
