### ISSUE TITLE
State stuck on BUFFERING - iOS

### ISSUE THREAD

**Issue by fxsalazar** [hoanglm4/flutter_youtube_view#19]
Try to embed the `YouTubeDefaultWidget` from the example in my app without success:
```
flutter: onReady
flutter: onStateChange state = UNSTARTED
flutter: onStateChange state = BUFFERING
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
```
Set autoplay to true, but i cannot even see the video frame.

**Comment by hoanglm4** [comment]
Hi @fxsalazar ,
Please add (key=io.flutter.embedded_views_preview value=YES) into  Info.plist.
https://github.com/flutter/flutter/issues/19030#issuecomment-437534853

**Comment by fxsalazar** [comment]
This should be put on the README as part of **How to use**. Thx.

**Comment by fxsalazar** [comment]
@hoanglm4 I'm having another issue. Why the widget is rebuilding itself twice, calling its parent to rebuild? I'm fetching data (the video url) with a StreamBuilder and this causing an infinite loop between the fetching and the building of the player.
