### ISSUE TITLE
java.lang.Double cannot be cast to java.lang.Float

### ISSUE THREAD

**Issue by davidgalarza** [hoanglm4/flutter_youtube_view#2]
My code:
`game.getLyric().getPhraseAt(1).startTime - 1000) /
                        1000   `

That return for example 80.805

When I call 

`this._controller.seekTo(
                        ((game.getLyric().getPhraseAt(1).startTime - 1000) /
                            1000))`

I have the following issue:

` Failed to handle method call
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at com.hoanglm.flutteryoutubeview.FlutterYoutubeView.seekTo(FlutterYoutubeView.kt:181)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at com.hoanglm.flutteryoutubeview.FlutterYoutubeView.onMethodCall(FlutterYoutubeView.kt:106)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#plugins.hoanglm.com/youtube_3(19122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter (19122): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.lang.Double cannot be cast to java.lang.Float, null)
E/flutter (19122): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (19122): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (19122): <asynchronous suspension>
E/flutter (19122): #2      FlutterYoutubeViewController.seekTo (package:flutter_youtube_view/flutter_youtube_view.dart:115:20)`

**Comment by hoanglm4** [comment]
Hello @davidgalarza ,

Thank you for report. This bug is fixed in https://github.com/hoanglm4/flutter_youtube_view/pull/3.

**Comment by hoanglm4** [comment]
Hello @davidgalarza 
Please check this issue in version flutter_youtube_view: ^1.1.0
Thanks

**Comment by davidgalarza** [comment]
Yes in version flutter_youtube_view: ^1.1.0, works perfectly.
