### ISSUE TITLE
startSeconds doesn't work in iOS

### ISSUE THREAD

**Issue by wongni** [hoanglm4/flutter_youtube_view#23]
startSeconds doesn't work in iOS when passing non-zero value to FlutterYoutubeView constructor or loadOrCueVideo() method. 

The same things work well in Android.

**Comment by hoanglm4** [comment]
Hi @wongni ,

This is bug. I will fix it.
Thanks

**Comment by hoanglm4** [comment]
Fixed in version: 1.1.6
