### ISSUE TITLE
App release when use this libs

### ISSUE THREAD

**Issue by hunglv21** [hoanglm4/flutter_youtube_view#30]
App release when use this libs:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

**Comment by hoanglm4** [comment]
Hi @hunglv21 ,
This lib only using WKWebView. Which class using UIWebView. Can you help me search in your iOS project ?
Thanks
