### ISSUE TITLE
version 1.1.7 not working with swift 5

### ISSUE THREAD

**Issue by tamirrab** [hoanglm4/flutter_youtube_view#43]
version 1.1.7 not working with swift 5

**Comment by Faiyyaz** [comment]
Even i m facing the same issue some code has been deprecated in swift 4.2

**Comment by hoanglm4** [comment]
This request already merged, will release soon: https://github.com/hoanglm4/flutter_youtube_view/pull/44

**Comment by dahabit** [comment]
@hoanglm4  Hello, any updates regarding the new release?

**Comment by davidgalarza** [comment]
Any update?

**Comment by hoanglm4** [comment]
Hi All,

I have deployed in 1.1.8. 
Thank you all
