### ISSUE TITLE
Cannot build apk

### ISSUE THREAD

**Issue by abhikb101** [hoanglm4/flutter_youtube_view#46]
I have used this plugin in my app but when I am trying to build it, it throws this error:
`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_youtube_view'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. `

**Comment by hoanglm4** [comment]
Hi @abhikb101 ,
 
Please run: flutter doctor   to check your development environment .
https://flutter.dev/docs/get-started/install/macos

**Comment by abhikb101** [comment]
Hi @hoanglm4 ,
I ran flutter doctor and everthing came up fine. Furthermore, I have been able to use the plugin in debug and profile mode. The issue arises whenever I try to build the Apk in release mode.
Thanks

**Comment by hoanglm4** [comment]
Hi @abhikb101 ,
you can define ANDROID_HOME environment variable. This issue will be resolve.

**Comment by abhikb101** [comment]
Thank you for the response. The error was  with my java version. Downgrading it to java 8 solved this for me.
