### ISSUE TITLE
for web

### ISSUE THREAD

**Issue by Red2Cat** [hoanglm4/flutter_youtube_view#50]
after web compiling i got only white screen, if push run button in studio then... 

![image](https://user-images.githubusercontent.com/66417421/83802159-5433d680-a6bb-11ea-8118-a0e5a1d3dc42.png)

**Comment by fcsvndev** [comment]
Hi @Red2Cat ,
Currently, this plugin only support for android/iOS

**Comment by hoanglm4** [comment]
Hi @Red2Cat ,
Currently, this plugin only support for android/iOS
