### ISSUE TITLE
Unable to build ios release

### ISSUE THREAD

**Issue by amitojsingh366** [hoanglm4/flutter_youtube_view#51]
Getting issue 'CocoaPods could not find compatible versions for pod "flutter_youtube_view":'

**Comment by amitojsingh366** [comment]
also had this line show up:
Specs satisfying the `flutter_youtube_view (from `.symlinks/plugins/flutter_youtube_view/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by amitojsingh366** [comment]
now after changing deployment target I'm getting:
fatal error: module 'flutter_youtube_view' not found
    @import flutter_youtube_view;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by rwrz** [comment]
Try to clear your build. When you change the Pod related stuff all kinds of problems happens.

`flutter clean`

you can even try to clear you pod cache:

`pod cache clean --all`

**Comment by M001T** [comment]
Dont work

**Comment by M001T** [comment]
> Try to clear your build. When you change the Pod related stuff all kinds of problems happens.
> 
> `flutter clean`
> 
> you can even try to clear you pod cache:
> 
> `pod cache clean --all`

Dont Work

**Comment by hoanglm4** [comment]
Hi,
Please try to using flutter_youtube_view: ^1.1.9
