### ISSUE TITLE
Supporting the new Android plugins APIs v2

### ISSUE THREAD

**Issue by komaromil** [hoanglm4/flutter_youtube_view#57]
Is it possible to upgrade?

**Comment by rwrz** [comment]
what plugins?

**Comment by komaromil** [comment]
flutter_youtube_view - android part
It uses PluginRegistry.Registrar and we should migrate our app v2 Android embedding and read the article should change it here also sometime...
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by rwrz** [comment]
Hmm... It's true.
I can take a look at it next month. But don't worry, if no one upgrades it, I will before it deprecates.

**Comment by komaromil** [comment]
Thank you

**Comment by hoanglm4** [comment]
Thanks @rwrz 
Welcome to your pull request

**Comment by hoanglm4** [comment]
fixed: flutter_youtube_view: 1.1.10
