### ISSUE TITLE
flutter_youtube_view-1.1.0/ios/Classes/FlutterYoutubeViewPlugin.m:2:9: 'flutter_youtube_view/flutter_youtube_view-Swift.h' file not found

### ISSUE THREAD

**Issue by kyungjoongo** [hoanglm4/flutter_youtube_view#6]
I get the following error when building on iOS:
/ FlutterYoutubeView Plugin.m2: 9: 'flutter_youtube_view / flutter_youtube_view-swift.h' file not found
Please let me know the solution ~

**Comment by hoanglm4** [comment]
Hello @kyungjoongo ,
This error happens to all flutter projects that import plugins that need Swift support. To fix it:
Don't rebuild the project with swift support. Instead create a fresh new empty project with swift support. Then just copy over all your dart files, assets & pubspec. Nothing else but that.

**Comment by kyungjoongo** [comment]
Thank you, I'll try.

**Comment by jigarfumakiya** [comment]
I have same issue.

**Comment by Faiyyaz** [comment]
I fixed the issue it was deprecated code in the avplayer folder of the lib
