### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by saelco** [hoanglm4/flutter_youtube_view#68]
e: C:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_youtube_view-2.0.0\android\src\main\kotlin\com\hoanglm\flutteryoutubeview\FlutterYoutubeViewPlugin.kt: (19, 1): Class 'FlutterYoutubeViewPlugin' is not abstract and does not implement abstract member public abstract fun onActivitySaveInstanceState(p0: Activity, p1: Bundle): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_youtube_view-2.0.0\android\src\main\kotlin\com\hoanglm\flutteryoutubeview\FlutterYoutubeViewPlugin.kt: (143, 5): 'onActivitySaveInstanceState' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_youtube_view:compileDebugKotlin'.
> Compilation error. See log for more details

How to fix it?

**Comment by jayjah** [comment]
Same here:

``` 
[        ] e: /Users/markuskrebs/.asdf/installs/flutter/2.2.0-stable/.pub-cache/hosted/pub.dartlang.org/flutter_youtube_view-2.0.0/android/src/main/kotlin/com/hoanglm/flutteryoutubeview/FlutterYoutubeViewPlugin.kt: (19, 1): Class 'FlutterYoutubeViewPlugin' is not abstract and does not implement abstract member public abstract fun onActivitySaveInstanceState(p0: Activity, p1: Bundle): Unit defined in android.app.Application.ActivityLifecycleCallbacks
[        ] e: /Users/markuskrebs/.asdf/installs/flutter/2.2.0-stable/.pub-cache/hosted/pub.dartlang.org/flutter_youtube_view-2.0.0/android/src/main/kotlin/com/hoanglm/flutteryoutubeview/FlutterYoutubeViewPlugin.kt: (143, 5): 'onActivitySaveInstanceState' overrides nothing
[+5798 ms] > Task :flutter_youtube_view:compileDebugKotlin FAILED
[  +91 ms] > Task :app:processDebugManifestForPackage
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 189 actionable tasks: 43 executed, 146 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':flutter_youtube_view:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 16s
``` 

version: `flutter_youtube_view: ^2.0.0``

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-DE)
    • Flutter version 2.2.1 at /Users/markuskrebs/.asdf/installs/flutter/2.2.1-stable
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/markuskrebs/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/markuskrebs/Library/Android/sdk
    • Java binary at: /Users/markuskrebs/Library/Java/JavaVirtualMachines/corretto-1.8.0_292/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
```

**Comment by jayjah** [comment]
@saelco could you verify that my fix is helping in your case as well?

my branch with fix: https://github.com/jayjah/flutter_youtube_view.git

you could test it with an override in your `pubspec.yaml` file, e.G.:
```
dependency_overrides:

  flutter_youtube_view:
    git:
      url: https://github.com/jayjah/flutter_youtube_view.git
      ref: master
```

**Comment by saelco** [comment]
> 
> 
> @saelco could you verify that my fix is helping in your case as well?
> 
> my branch with fix: https://github.com/jayjah/flutter_youtube_view.git
> 
> you could test it with an override in your `pubspec.yaml` file, e.G.:
> 
> ```
> dependency_overrides:
> 
>   flutter_youtube_view:
>     git:
>       url: https://github.com/jayjah/flutter_youtube_view.git
>       ref: master
> ```

it works!

**Comment by saelco** [comment]
> 
> 
> > @saelco could you verify that my fix is helping in your case as well?
> > my branch with fix: https://github.com/jayjah/flutter_youtube_view.git
> > you could test it with an override in your `pubspec.yaml` file, e.G.:
> > ```
> > dependency_overrides:
> > 
> >   flutter_youtube_view:
> >     git:
> >       url: https://github.com/jayjah/flutter_youtube_view.git
> >       ref: master
> > ```
> 
> it works!

I'm waiting for the new version :)

**Comment by hoanglm4** [comment]
Hi all,

New version just pushed: flutter_youtube_view: ^2.0.1

Thanks all
