### ISSUE TITLE
jvm problem

### ISSUE THREAD

**Issue by gulmensedat** [hoanglm4/flutter_youtube_view#70]
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_youtube_view-2.0.2/android/src/main/kotlin/com/hoanglm/flutteryoutubeview/FlutterYoutubeView.kt](): (134, 30): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_youtube_view:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by davidgalarza** [comment]
Same here any update

**Comment by jayjah** [comment]
@gulmensedat @davidgalarza 
Please check the open PR [PR71](https://github.com/hoanglm4/flutter_youtube_view/pull/71) which aims to fix the issue you mentioned.

Please override the decency in your `pubspec.yaml` file with my fork to see if it resolves your problems as well. 

Keep in mind, you may run into troubles with the wrong Kotlin version. To resolve those issues set
the correct and last Kotlin version to your project as the following

 `ext.kotlin_version = '1.6.10'` into `build.gradle`

**Comment by jayjah** [comment]
#71

**Comment by davidgalarza** [comment]
> @gulmensedat @davidgalarza Please check the open PR [PR71](https://github.com/hoanglm4/flutter_youtube_view/pull/71) which aims to fix the issue you mentioned.
> 
> Please override the decency in your `pubspec.yaml` file with my fork to see if it resolves your problems as well.
> 
> Keep in mind, you may run into troubles with the wrong Kotlin version. To resolve those issues set the correct and last Kotlin version to your project as the following
> 
> `ext.kotlin_version = '1.6.10'` into `build.gradle`

@jayjah I've tried with your fork and using ext.kotlin_version = '1.6.10' on my build.gradle and i can confirm that it solves the issue. Is working like a charm.

**Comment by hoanglm4** [comment]
fixed in flutter_youtube_view: ^2.0.3
